### ISSUE TITLE
fenicsX

### ISSUE THREAD

**Issue by div-tyg** [BAMresearch/FenicsConcrete#12]
fenicsX implementation in fenics Concrete for linear elasticity example.

**Comment by srosenbu** [comment]
Thank you for pushing the example.

If we are planning on slowly replacing the FEniCS code with FEniCSX code, should this repo contain two setup.py? Or should the FEniCSX branch contain only FEniCSX code?

**Comment by srosenbu** [comment]
I just updated the branch such that the legacy code is in a separate folder (labeled "legacy_code") and you can install fenicsXconcrete via `pip install -e .`

**Comment by srosenbu** [comment]
Since the linear elasticity example works in FEniCSx, I recommend closing this issue. I renamed the branch to `main-FEniCSx` and it is now protected like `master`. Any further development on the FEniCSx version should be branched from `main-FEniCSx` and merged into it later.
