### ISSUE TITLE
General definition of a force sensor

### ISSUE THREAD

**Issue by eriktamsen** [BAMresearch/FenicsConcrete#2]
currently there is a ReactionForceBottom implemented. It would be good to have more flexible sensor definition, or at least a flexible option, with maybe some of the standard cases as a hard coded version for easy use.

**Comment by TTitscher** [comment]
If the forces of interested are axis-aligned, you could specify the DOF numbers from where to access the residual vector. And these dofs usually come from a DirichletBC. A reference for dolfin (without x) is [in here](https://bamresearch.github.io/fenics-constitutive/examples/helper.html#load-displacement-curve). OK, this is mixed with also computing the displacements at the those dofs, but can extract the relevant parts.

**Comment by eriktamsen** [comment]
has been addressed in [fenicsXconcrete](https://github.com/BAMresearch/FenicsXConcrete)
