### ISSUE TITLE
How/when/where to trigger the computation of the residual

### ISSUE THREAD

**Issue by eriktamsen** [BAMresearch/FenicsConcrete#5]
Currently the reaction force sensor assumes that a residual is given, which is hard coded in the linear elastic model, as this uses that sensor. This is not a good solution, just temporary and needs to be fixed

**Comment by TTitscher** [comment]
We had a similar discussion over at fenics-constitive, I remember. 
The residual needs to be computed anyways, so I suggest having a `residual` member where the residual is stored before applying the boundary conditions. This is what I tried for dolfinx [here](https://github.com/TTitscher/Failure-modes-in-concrete-compression/blob/4755bbf3fdaf9336c82d34096a52921f0613ebff/code/problem.py#L111). 

One way to evaluate it is to [pass this vector to a `LoadSensor.__init__`](https://github.com/TTitscher/Failure-modes-in-concrete-compression/blob/4755bbf3fdaf9336c82d34096a52921f0613ebff/code/experiments.py#L10) and [extract the DOF values in `__call__`](https://github.com/TTitscher/Failure-modes-in-concrete-compression/blob/4755bbf3fdaf9336c82d34096a52921f0613ebff/code/experiments.py#L15).

**Comment by eriktamsen** [comment]
will be addressed in [fenicsXconcrete](https://github.com/BAMresearch/FenicsXConcrete)
